version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80' # Пробрасываем порт 80
    volumes:
      - .:/app # Монтируем локальные файлы (опционально, можно убрать в production)
      - /app/node_modules
