version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    networks:
      - my_network

  lemon_bank-lemon_bank_app:
    image: lemon_bank-lemon_bank_app:latest
    networks:
      - my_network

  webhook-tilda-webhook:
    image: webhook-tilda-webhook:latest
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
