version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:5173'
    networks:
      - my_network
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_HOST=0.0.0.0
    command: npm run dev -- --host

networks:
  my_network:
    external: true
