import { UserRole, UserStatus, type User } from '@/types/user'

export const MOCK_USERS: User[] = [
  {
    id: '001',
    fullname: 'Анна Смирнова',
    department: 'Frontend Development',
    email: 'a.smirnova@zarplata.ru',
    lemons: 50,
    diamonds: 2,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '002',
    fullname: 'Михаил Иванов',
    department: 'Backend Development',
    email: 'm.ivanov@zarplata.ru',
    lemons: 75,
    diamonds: 5,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '003',
    fullname: 'Елена Петрова',
    department: 'HR',
    email: 'e.petrova@zarplata.ru',
    lemons: 30,
    diamonds: 1,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '004',
    fullname: 'Дмитрий Козлов',
    department: 'DevOps',
    email: 'd.kozlov@zarplata.ru',
    lemons: 100,
    diamonds: 8,
    status: UserStatus.ACTIVE,
    role: UserRole.ADMIN,
  },
  {
    id: '005',
    fullname: 'Ольга Соколова',
    department: 'QA',
    email: 'o.sokolova@zarplata.ru',
    lemons: 45,
    diamonds: 3,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '006',
    fullname: 'Сергей Волков',
    department: 'Backend Development',
    email: 's.volkov@zarplata.ru',
    lemons: 60,
    diamonds: 4,
    status: UserStatus.INACTIVE,
    role: UserRole.USER,
  },
  {
    id: '007',
    fullname: 'Мария Морозова',
    department: 'Frontend Development',
    email: 'm.morozova@zarplata.ru',
    lemons: 85,
    diamonds: 6,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '008',
    fullname: 'Александр Новиков',
    department: 'Product Management',
    email: 'a.novikov@zarplata.ru',
    lemons: 90,
    diamonds: 7,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '009',
    fullname: 'Екатерина Попова',
    department: 'Design',
    email: 'e.popova@zarplata.ru',
    lemons: 40,
    diamonds: 2,
    status: UserStatus.ACTIVE,
    role: UserRole.USER,
  },
  {
    id: '010',
    fullname: 'Игорь Лебедев',
    department: 'Security',
    email: 'i.lebedev@zarplata.ru',
    lemons: 70,
    diamonds: 5,
    status: UserStatus.ACTIVE,
    role: UserRole.ADMIN,
  },
]
